/**
 * Source bundle location and integrity checking (spec 03, REQ-OPS-06, D7).
 *
 * Resolves the read-only adapter bundle for an agent from one of three locations (explicit
 * `--source`, the packaged copy, or the in-repo `../adapters/`), runs the minimal integrity
 * check, and fingerprints it (sourceHash + skills + files). Fallible operations return
 * `Result<T, E>` and never throw for expected errors. Zero runtime dependencies.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  type AgentId,
  type Result,
  type InstallerError,
  ok,
  err,
  BUNDLE_REQUIRED_PATHS,
} from "./types.js";
import { computeSourceHash, listBundleFiles } from "./hash.js";

/** Options for bundle resolution. */
export interface LocateBundleOpts {
  /**
   * Hidden test hook (`--source <dir>`, D7). When set, the bundle is resolved as
   * `<source>/<agent>` and the packaged / in-repo locations are NOT consulted.
   */
  source?: string;
}

/**
 * Aggregate of a located, integrity-checked, fingerprinted bundle (spec 03 §3.7).
 */
export interface LocatedSource {
  /** Absolute path to the agent bundle root (e.g. `.../adapters/claude`). */
  readonly root: string;
  /** sha256 over the bundle's sorted-path file set — the drift anchor (`manifest.sourceHash`). */
  readonly sourceHash: string;
  /** Installed skill ids (the bundle's `skills/*` dir names) for `manifest.skills`. */
  readonly skills: readonly string[];
  /** Per-file inventory (`{ relpath, sha256 }`, sorted by POSIX relpath) — the planner's input. */
  readonly files: ReadonlyArray<{ readonly relpath: string; readonly sha256: string }>;
}

/**
 * Locate the read-only adapter bundle directory for `agent` (D7, REQ-OPS-06).
 *
 * Resolution order (first existing directory wins): `opts.source/<agent>`, then
 * `<installerPkgRoot>/adapters/<agent>`, then `<repoRoot>/adapters/<agent>` (both derived from
 * `import.meta.url`, cwd-independent).
 *
 * @returns ok(absolutePath) when a candidate dir exists; err(SOURCE_MISSING) naming the expected
 *          path + remedy otherwise.
 */
export function locateBundle(
  agent: AgentId,
  opts: LocateBundleOpts = {},
): Result<string> {
  for (const candidate of bundleCandidates(agent, opts)) {
    if (isDirectory(candidate)) return ok(candidate);
  }
  const expected = primaryExpectedPath(agent, opts);
  return err<InstallerError>({
    code: "SOURCE_MISSING",
    agent,
    path: expected,
    message:
      `no source bundle for agent "${agent}" — expected an adapters directory at ${expected}. ` +
      `The bundle is generated by the adapters build; run it (or pass --source <dir>) before installing.`,
    remedy: "run the adapters build to generate adapters/<agent>/, or pass --source <dir>",
  });
}

/**
 * Minimal integrity check for a located bundle (REQ-OPS-06). Valid iff the `BUNDLE_REQUIRED_PATHS`
 * are present: `skills/` is a non-empty dir, `scripts/forge-root.sh` exists, and (gemini)
 * `gemini-extension.json` exists. Does NOT require `.claude-plugin/plugin.json` or
 * `epic-manifest.py` (IR-1 / OQ-A).
 *
 * @returns ok(undefined) when every required path is present; err(SOURCE_INVALID) naming the
 *          first missing/invalid required path otherwise.
 */
export function checkIntegrity(
  bundlePath: string,
  agent: AgentId,
): Result<void> {
  const skillsDir = path.join(bundlePath, "skills");
  if (!isDirectory(skillsDir) || !hasEntries(skillsDir)) {
    return invalid(agent, skillsDir, "skills/ is missing or empty");
  }

  const required = requiredPathsFor(agent).filter((rel) => rel !== "skills");
  for (const rel of required) {
    const abs = path.join(bundlePath, rel);
    if (!fs.existsSync(abs)) {
      return invalid(agent, abs, `required path "${rel}" is missing`);
    }
  }
  return ok(undefined);
}

/**
 * List the skill ids a bundle contains: the directory names directly under
 * `<bundlePath>/skills/` (REQ-SCALE-02). Enumerates DIRECTORY NAMES ONLY and never opens a skill
 * file. Returned sorted (byte-wise).
 */
export function listBundleSkills(bundlePath: string): string[] {
  const skillsDir = path.join(bundlePath, "skills");
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(skillsDir, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

/**
 * Locate, integrity-check, and fingerprint one agent's bundle in a single call (spec 03 §3.7).
 *
 * @returns ok(LocatedSource) when the bundle exists and passes the integrity check; otherwise the
 *          exact err(SOURCE_MISSING) / err(SOURCE_INVALID) from locateBundle/checkIntegrity.
 */
export function locateSource(
  agent: AgentId,
  opts?: { source?: string },
): Result<LocatedSource> {
  const located = locateBundle(agent, opts);
  if (!located.ok) return located; // SOURCE_MISSING

  const integrity = checkIntegrity(located.value, agent);
  if (!integrity.ok) return integrity; // SOURCE_INVALID

  return ok({
    root: located.value,
    sourceHash: computeSourceHash(located.value),
    skills: listBundleSkills(located.value),
    files: listBundleFiles(located.value),
  });
}

// ---------------------------------------------------------------------------
// Internal helpers (module-private — spec 03 §4.1, §4.2)
// ---------------------------------------------------------------------------

/** dist/source.js at runtime → its dir is <installerPkgRoot>/dist. */
function moduleDir(): string {
  return path.dirname(fileURLToPath(import.meta.url));
}

/** <installerPkgRoot> = parent of dist/. */
function installerPkgRoot(): string {
  return path.resolve(moduleDir(), "..");
}

/** <repoRoot> = parent of installer/. */
function repoRoot(): string {
  return path.resolve(installerPkgRoot(), "..");
}

/** The ordered candidate bundle dirs for an agent (spec 03 §3.1 table). */
function bundleCandidates(agent: AgentId, opts: LocateBundleOpts): string[] {
  // Explicit --source is exclusive: the packaged / in-repo locations are NOT consulted (spec §3.1).
  if (opts.source) return [path.resolve(opts.source, agent)];
  const candidates: string[] = [];
  candidates.push(path.join(installerPkgRoot(), "adapters", agent)); // packaged copy (D7)
  candidates.push(path.join(repoRoot(), "adapters", agent)); // in-repo dev (C-3)
  return candidates;
}

/** The most actionable expected path to name in a SOURCE_MISSING error (REQ-OBS-02). */
function primaryExpectedPath(agent: AgentId, opts: LocateBundleOpts): string {
  return opts.source
    ? path.resolve(opts.source, agent)
    : path.join(repoRoot(), "adapters", agent);
}

/** common + per-agent required paths (from BUNDLE_REQUIRED_PATHS, 00 §6). */
function requiredPathsFor(agent: AgentId): readonly string[] {
  const perAgent = BUNDLE_REQUIRED_PATHS.perAgent[agent] ?? [];
  return [...BUNDLE_REQUIRED_PATHS.common, ...perAgent];
}

/** Construct the SOURCE_INVALID error naming the offending path (REQ-OBS-02). */
function invalid(agent: AgentId, badPath: string, why: string): Result<never> {
  return err<InstallerError>({
    code: "SOURCE_INVALID",
    agent,
    path: badPath,
    message: `source bundle for agent "${agent}" is invalid: ${why} (at ${badPath}).`,
    remedy: "re-run the adapters build to regenerate a complete bundle",
  });
}

/** True iff `p` exists and is a directory. */
function isDirectory(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** True iff directory `p` has at least one entry (used for the non-empty `skills/` check). */
function hasEntries(p: string): boolean {
  try {
    return fs.readdirSync(p).length > 0;
  } catch {
    return false;
  }
}
