#!/bin/sh
# setup-docs.sh — idempotent content symlinker for the docs site.
# Generated by doc-site (contentMode: symlink|mixed). Do not edit by hand;
# re-running the generator regenerates this file (a hand edit is detected and the
# file is skipped — see .doc-site-scaffold.json provenance).
#
# Creates RELATIVE-path symlinks from the Starlight content collection to the
# repo-root markdown that is the single source of truth. Idempotent: re-running
# yields the same links (ln -sf / ln -sfn) and a no-op git diff modulo the
# regenerated .astro cache.
set -eu

# --- Resolve repo root and the docs content collection directory -------------
# The script lives at docs-site/setup-docs.sh, so repo root is computed
# relative to the script's own location (works regardless of caller CWD).
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
DOCS_PKG_DIR="$REPO_ROOT/docs-site"
CONTENT_DIR="$DOCS_PKG_DIR/src/content/docs"

echo "Setting up documentation symlinks..."
echo "  Repo root:   $REPO_ROOT"
echo "  Content dir: $CONTENT_DIR"

mkdir -p "$CONTENT_DIR"

# --- Safety: refuse any source path that escapes the repo tree (REQ-SEC-02) --
# Canonicalize the resolved target and assert it is inside $REPO_ROOT before
# linking. See 08-rerun-and-verification.md for the authoritative policy.
assert_inside_repo() {
  # $1 = repo-relative source path (the manifest `from` value, or images dir)
  _src="$REPO_ROOT/$1"
  _dir=$(dirname "$_src")
  if [ ! -d "$_dir" ]; then
    echo "ERROR: source directory does not exist: $_dir" >&2
    exit 1
  fi
  # Canonicalize the directory (follows .. and symlinks) then re-append basename.
  _canon_dir=$(cd "$_dir" && pwd -P)
  _canon="$_canon_dir/$(basename "$_src")"
  _root_canon=$(cd "$REPO_ROOT" && pwd -P)
  case "$_canon" in
    "$_root_canon"/*) : ;;  # inside repo — ok
    *)
      echo "ERROR: refusing symlink target outside repo root: $1" >&2
      echo "       resolved to: $_canon (repo root: $_root_canon)" >&2
      exit 1
      ;;
  esac
}

# --- rel_path: pure-POSIX relative path from $1 (dir) to $2 (file/dir) --------
# Both args are absolute. Emits a path relative to $1 that resolves to $2, using
# only canonicalized absolute prefixes (no realpath --relative-to, which is GNU).
rel_path() {
  _from=$(cd "$1" && pwd -P)
  _to_dir=$(cd "$(dirname "$2")" && pwd -P)
  _to="$_to_dir/$(basename "$2")"
  _common="$_from"
  _up=""
  while [ "${_to#"$_common"/}" = "$_to" ] && [ "$_common" != "/" ]; do
    _common=$(dirname "$_common")
    _up="../$_up"
  done
  if [ "$_common" = "/" ]; then
    _rest="${_to#/}"
  else
    _rest="${_to#"$_common"/}"
  fi
  printf '%s%s\n' "$_up" "$_rest"
}

# --- link_file: relative-path symlink for a single source=symlink page -------
# $1 = repo-relative source markdown (manifest `from`); $2 = slug (dest name)
link_file() {
  assert_inside_repo "$1"
  if [ ! -f "$REPO_ROOT/$1" ]; then
    echo "ERROR: symlink source file not found: $1" >&2
    echo "       (manifest page '$2' references a missing 'from' target)" >&2
    exit 1
  fi
  _dest="$CONTENT_DIR/$2.md"
  mkdir -p "$(dirname "$_dest")"
  # Relative path FROM the destination's directory TO the source file.
  _rel=$(rel_path "$(dirname "$_dest")" "$REPO_ROOT/$1")
  ln -sf "$_rel" "$_dest"
  echo "  linked $2.md -> $_rel"
}

# --- link_dir: --no-dereference dir symlink (images/) -------------------------
# $1 = repo-relative source dir; $2 = dest name under content dir.
# CRITICAL: use ln -sfn (-n = --no-dereference). Without -n, a second run sees an
# existing symlink that points at a directory, dereferences it, and creates the
# new link *inside* the target dir (e.g. images/images), corrupting the tree.
link_dir() {
  assert_inside_repo "$1"
  if [ ! -d "$REPO_ROOT/$1" ]; then
    echo "ERROR: symlink source directory not found: $1" >&2
    exit 1
  fi
  _dest="$CONTENT_DIR/$2"
  _rel=$(rel_path "$(dirname "$_dest")" "$REPO_ROOT/$1")
  ln -sfn "$_rel" "$_dest"
  echo "  linked $2/ -> $_rel (no-dereference)"
}

# >>> manifest-managed symlinks (generated from docs.manifest.json at emit time)
# One link_file call per `source: "symlink"` page; native/unmanaged pages omitted.
link_file "docs/agents/claude.md" "agents/claude"
link_file "docs/agents/codex.md" "agents/codex"
link_file "docs/agents/copilot.md" "agents/copilot"
link_file "docs/agents/cursor.md" "agents/cursor"
link_file "docs/agents/gemini.md" "agents/gemini"
link_file "docs/architecture/forge-bootstrap/README.md" "forge-bootstrap/overview"
link_file "docs/architecture/forge-bootstrap/architecture.md" "forge-bootstrap/architecture"
link_file "docs/architecture/forge-bootstrap/cli-reference.md" "forge-bootstrap/cli-reference"
link_file "docs/architecture/forge-bootstrap/guides/integration.md" "forge-bootstrap/guides/integration"
link_file "docs/architecture/epic-orchestration/README.md" "epic-orchestration/overview"
link_file "docs/architecture/epic-orchestration/architecture.md" "epic-orchestration/architecture"
link_file "docs/architecture/epic-orchestration/cli-reference.md" "epic-orchestration/cli-reference"
link_file "docs/architecture/epic-orchestration/guides/integration.md" "epic-orchestration/guides/integration"
# Directory symlink for images so `images/<x>.svg` resolves on GitHub and Starlight:
link_dir "docs/images" "images"
# <<< manifest-managed symlinks

# --- Clear Astro's content cache so the build re-scans after relinking --------
rm -rf "$DOCS_PKG_DIR/.astro" "$DOCS_PKG_DIR/node_modules/.astro"

echo "Done."
